elearningProject/force-app/main/default/objects/Option__c/Option__c.object-meta.xml
<CustomObject>
    <label>Option</label>
    <nameField>
        <label>Option Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Options</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

elearningProject/force-app/main/default/objects/Option__c/fields/isRight__c.field-meta.xml
<CustomField>
    <fullName>isRight__c</fullName>
    <defaultValue>false</defaultValue>
    <label>isRight</label>
    <type>Checkbox</type>
</CustomField>

elearningProject/force-app/main/default/objects/Question_s_Answer__c/Question_s_Answer__c.object-meta.xml
<CustomObject>
    <label>Question&apos;s Answer</label>
    <nameField>
        <displayFormat>OF-{0000}</displayFormat>
        <label>Question&apos;s Answer Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Question&apos;s Answers</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

elearningProject/force-app/main/default/objects/Question_s_Answer__c/fields/Option__c.field-meta.xml
<CustomField>
    <fullName>Option__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Option</label>
    <referenceTo>Option__c</referenceTo>
    <relationshipLabel>Question&apos;s Answers</relationshipLabel>
    <relationshipName>Question_s_Answers</relationshipName>
    <type>Lookup</type>
</CustomField>

elearningProject/force-app/main/default/objects/Question_s_Answer__c/fields/Unit_progress__c.field-meta.xml
<CustomField>
    <fullName>Unit_progress__c</fullName>
    <label>Unit progress</label>
    <referenceTo>Unit_progress__c</referenceTo>
    <relationshipLabel>Question&apos;s Answers</relationshipLabel>
    <relationshipName>Question_s_Answers</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

elearningProject/force-app/main/default/objects/Unit__c/fields/Max_Score__c.field-meta.xml
<CustomField>
    <fullName>Max_Score__c</fullName>
    <label>Max Score</label>
    <precision>4</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

elearningProject/force-app/main/default/objects/Unit_progress__c/Unit_progress__c.object-meta.xml
<CustomObject>
    <label>Unit progress</label>
    <nameField>
        <displayFormat>OF-{0000}</displayFormat>
        <label>Unit progress Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Units progress</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

elearningProject/force-app/main/default/objects/Unit_progress__c/fields/Num_of_tries__c.field-meta.xml
<CustomField>
    <fullName>Num_of_tries__c</fullName>
    <label>Num of tries</label>
    <precision>2</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

elearningProject/force-app/main/default/objects/Unit_progress__c/fields/Student_Unit_Score__c.field-meta.xml
<CustomField>
    <fullName>Student_Unit_Score__c</fullName>
    <label>Student Unit Score</label>
    <precision>4</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

elearningProject/force-app/main/default/objects/Unit_progress__c/fields/Unit__c.field-meta.xml
<CustomField>
    <fullName>Unit__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Unit</label>
    <referenceTo>Unit__c</referenceTo>
    <relationshipLabel>Units progress</relationshipLabel>
    <relationshipName>Units_progress</relationshipName>
    <type>Lookup</type>
</CustomField>

elearningProject/force-app/main/default/objects/Unit_progress__c/fields/Unit_completed__c.field-meta.xml
<CustomField>
    <fullName>Unit_completed__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Unit completed</label>
    <type>Checkbox</type>
</CustomField>

elearningProject/force-app/main/default/objects/Unit_progress__c/fields/Unit_Stage__c.field-meta.xml
<CustomField>
    <fullName>Unit_Stage__c</fullName>
    <label>Unit Stage</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Draft</fullName>
                <default>true</default>
                <label>Draft</label>
            </value>
            <value>
                <fullName>Answered</fullName>
            </value>
            <value>
                <fullName>Success</fullName>
            </value>
            <value>
                <fullName>Fail</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

elearningProject/force-app/main/default/classes/UnitResponseTrigger.cls
public class UnitResponseTrigger{

    public static void onBeforeUpdate(List<Unit_progress__c> unitRespList, Map<Id,Unit_progress__c> oldUnitRespMap){
        List<Unit_progress__c> answeredUnitRespList = new List<Unit_progress__c>();
        for(Unit_progress__c unitResp : unitRespList){
            if(unitResp.Unit_Stage__c == 'Answered' && oldUnitRespMap.get(unitResp.Id).Unit_Stage__c == 'Draft'){
                answeredUnitRespList.add(unitResp);
            }
        }

        validateAnswers(answeredUnitRespList);

    }

    public static void onAfterUpdate(List<Unit_progress__c> unitRespList, Map<Id,Unit_progress__c> oldUnitRespMap){
        List<Unit_progress__c> correctUnitRespList = new List<Unit_progress__c>();
        for (Unit_progress__c unitResp : unitRespList){
            if(unitResp.Unit_completed__c && !oldUnitRespMap.get(unitResp.Id).Unit_completed__c){
                correctUnitRespList.add(unitResp);
            }
        }
        updateUserPoints(correctUnitRespList);

    }

    private static void updateUserPoints(List<Unit_progress__c> correctUnitRespList){
        Set<Id> userIds = new Set<Id>();
        for(Unit_progress__c unitResp : correctUnitRespList){
            userIds.add(unitResp.UserId__c);
        }

        Map<Id,User> usersMap = new Map<Id,User>([SELECT ID, CumulativePoints__c FROM USER WHERE Id in :userIds]);

        for (Unit_progress__c unitResp : correctUnitRespList){
            User us = usersMap.get(unitResp.UserId__c);
            us.CumulativePoints__c += unitResp.Student_Unit_Score__c;
        }

        update usersMap.values();
    }
    

    private static void validateAnswers(List<Unit_progress__c> unitRespList){
        
        Map<Id,Unit_progress__c> unitRespFromDbMap = new Map<Id,Unit_progress__c>([SELECT Id, Student_Unit_Score__c, Unit__r.Max_Score__c,(SELECT Id, Option__r.IsRight__c FROM Question_s_Answers__r) FROM Unit_progress__c WHERE Id in 
        : unitRespList]);

        //200
        for(Unit_progress__c unitResp : unitRespList){

            Unit_progress__c unitRespFromDb = unitRespFromDbMap.get(unitResp.Id);

            unitResp.Unit_completed__c = true;
            unitResp.Unit_Stage__c = 'Success';
            //10
            for(Question_s_Answer__c questionResp : unitRespFromDb.Question_s_Answers__r){
                //10 * 200 = 2000
                if(!questionResp.Option__r.IsRight__c){
                    unitResp.Unit_completed__c = false;
                    unitResp.Unit_Stage__c = 'Fail';
                    break;
                }
            }
            if (unitResp.Unit_completed__c){
                Double maxScore = unitResp.Unit__r.Max_Score__c;
                if (unitResp.Num_of_tries__c==1) {
                    unitResp.Student_Unit_Score__c = maxScore;
                } else if (unitResp.Num_of_tries__c == 2){
                    unitResp.Student_Unit_Score__c = maxScore/2;
                } else {
                    unitResp.Student_Unit_Score__c = maxScore/4;
                }
            }
        }
    }



}