elearningProject/force-app/main/default/objects/Module__c/Module__c.object-meta.xml
<CustomObject>
    <label>Module</label>
    <nameField>
        <label>Module Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Modules</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

elearningProject/force-app/main/default/objects/Module__c/fields/Estimated_Time__c.field-meta.xml
<CustomField>
    <fullName>Estimated_Time__c</fullName>
    <label>Estimated Time</label>
    <summarizedField>Unit__c.Estimated_time__c</summarizedField>
    <summaryForeignKey>Unit__c.Module__c</summaryForeignKey>
    <summaryOperation>sum</summaryOperation>
    <type>Summary</type>
</CustomField>

elearningProject/force-app/main/default/objects/Module__c/fields/Max_Score__c.field-meta.xml
<CustomField>
    <fullName>Max_Score__c</fullName>
    <label>Max Score</label>
    <summarizedField>Unit__c.Max_Score__c</summarizedField>
    <summaryForeignKey>Unit__c.Module__c</summaryForeignKey>
    <summaryOperation>sum</summaryOperation>
    <type>Summary</type>
</CustomField>

elearningProject/force-app/main/default/objects/Module_Progress__c/Module_Progress__c.object-meta.xml
<CustomObject>
    <label>Module Progress</label>
    <nameField>
        <displayFormat>OF-{0000}</displayFormat>
        <label>Module Progress Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Modules Progress</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

elearningProject/force-app/main/default/objects/Module_Progress__c/fields/Module_Status__c.field-meta.xml
<CustomField>
    <fullName>Module_Status__c</fullName>
    <label>Module Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>In progress</fullName>
            </value>
            <value>
                <fullName>Completed</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

elearningProject/force-app/main/default/objects/Module_Progress__c/fields/User__c.field-meta.xml
<CustomField>
    <fullName>User__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>User</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Modules_Progress</relationshipName>
    <type>Lookup</type>
</CustomField>

elearningProject/force-app/main/default/objects/Option__c/Option__c.object-meta.xml
<CustomObject>
    <label>Option</label>
    <nameField>
        <label>Option Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Options</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

elearningProject/force-app/main/default/objects/Option__c/fields/Description__c.field-meta.xml
<CustomField>
    <fullName>Description__c</fullName>
    <label>Description</label>
    <length>800</length>
    <type>LongTextArea</type>
</CustomField>

elearningProject/force-app/main/default/objects/Option__c/fields/isRight__c.field-meta.xml
<CustomField>
    <fullName>isRight__c</fullName>
    <defaultValue>false</defaultValue>
    <label>isRight</label>
    <type>Checkbox</type>
</CustomField>

elearningProject/force-app/main/default/objects/Option__c/fields/Question__c.field-meta.xml
<CustomField>
    <fullName>Question__c</fullName>
    <label>Question</label>
    <referenceTo>Question__c</referenceTo>
    <relationshipLabel>Options</relationshipLabel>
    <relationshipName>Options</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

elearningProject/force-app/main/default/objects/Question__c/Question__c.object-meta.xml
<CustomObject>
    <label>Question</label>
    <nameField>
        <label>Question Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Questions</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

elearningProject/force-app/main/default/objects/Question__c/fields/Query__c.field-meta.xml
<CustomField>
    <fullName>Query__c</fullName>
    <label>Query</label>
    <length>200</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

elearningProject/force-app/main/default/objects/Question_s_Answer__c/Question_s_Answer__c.object-meta.xml
<CustomObject>
    <label>Question&apos;s Answer</label>
    <nameField>
        <displayFormat>OF-{0000}</displayFormat>
        <label>Question&apos;s Answer Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Question&apos;s Answers</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

elearningProject/force-app/main/default/objects/Question_s_Answer__c/fields/Option__c.field-meta.xml
<CustomField>
    <fullName>Option__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Option</label>
    <referenceTo>Option__c</referenceTo>
    <relationshipLabel>Question&apos;s Answers</relationshipLabel>
    <relationshipName>Question_s_Answers</relationshipName>
    <type>Lookup</type>
</CustomField>

elearningProject/force-app/main/default/objects/Question_s_Answer__c/fields/Question__c.field-meta.xml
<CustomField>
    <fullName>Question__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Question</label>
    <referenceTo>Question__c</referenceTo>
    <relationshipLabel>Question&apos;s Answers</relationshipLabel>
    <relationshipName>Question_s_Answers</relationshipName>
    <type>Lookup</type>
</CustomField>

elearningProject/force-app/main/default/objects/Question_s_Answer__c/fields/Unit_progress__c.field-meta.xml
<CustomField>
    <fullName>Unit_progress__c</fullName>
    <label>Unit progress</label>
    <referenceTo>Unit_progress__c</referenceTo>
    <relationshipLabel>Question&apos;s Answers</relationshipLabel>
    <relationshipName>Question_s_Answers</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

elearningProject/force-app/main/default/objects/Trail__c/Trail__c.object-meta.xml
<CustomObject>
    <label>Trail</label>
    <nameField>
        <label>Trail Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Trails</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

elearningProject/force-app/main/default/objects/Trail__c/fields/Trail_Estimated_Time__c.field-meta.xml
<CustomField>
    <fullName>Trail_Estimated_Time__c</fullName>
    <label>Trail Estimated Time</label>
    <summarizedField>Trail_Module__c.Estimated_time__c</summarizedField>
    <summaryForeignKey>Trail_Module__c.Trail__c</summaryForeignKey>
    <summaryOperation>sum</summaryOperation>
    <type>Summary</type>
</CustomField>

elearningProject/force-app/main/default/objects/Trail__c/fields/Trail_Max_Score__c.field-meta.xml
<CustomField>
    <fullName>Trail_Max_Score__c</fullName>
    <label>Trail Max Score</label>
    <summarizedField>Trail_Module__c.Max_Score__c</summarizedField>
    <summaryForeignKey>Trail_Module__c.Trail__c</summaryForeignKey>
    <summaryOperation>sum</summaryOperation>
    <type>Summary</type>
</CustomField>

elearningProject/force-app/main/default/objects/Trail_Module__c/Trail_Module__c.object-meta.xml
<CustomObject>
    <label>Trail Module</label>
    <nameField>
        <displayFormat>OF-{0000}</displayFormat>
        <label>Trail Module Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Trail Modules</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

elearningProject/force-app/main/default/objects/Trail_Module__c/fields/Estimated_time__c.field-meta.xml
<CustomField>
    <fullName>Estimated_time__c</fullName>
    <label>Estimated time</label>
    <precision>4</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

elearningProject/force-app/main/default/objects/Trail_Module__c/fields/Max_Score__c.field-meta.xml
<CustomField>
    <fullName>Max_Score__c</fullName>
    <label>Max Score</label>
    <precision>5</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

elearningProject/force-app/main/default/objects/Unit__c/fields/Content__c.field-meta.xml
<CustomField>
    <fullName>Content__c</fullName>
    <label>Content</label>
    <length>3600</length>
    <type>LongTextArea</type>
</CustomField>

elearningProject/force-app/main/default/objects/Unit__c/fields/Estimated_time__c.field-meta.xml
<CustomField>
    <fullName>Estimated_time__c</fullName>
    <description>Estimated time in minutes</description>
    <label>Estimated time</label>
    <precision>4</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

elearningProject/force-app/main/default/objects/Unit__c/fields/Max_Score__c.field-meta.xml
<CustomField>
    <fullName>Max_Score__c</fullName>
    <label>Max Score</label>
    <precision>4</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

elearningProject/force-app/main/default/objects/Unit__c/fields/Test_Type__c.field-meta.xml
<CustomField>
    <fullName>Test_Type__c</fullName>
    <label>Test Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Multiple Choice</fullName>
            </value>
            <value>
                <fullName>Hands On Challenge</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

elearningProject/force-app/main/default/objects/Unit_progress__c/Unit_progress__c.object-meta.xml
<CustomObject>
    <label>Unit progress</label>
    <nameField>
        <displayFormat>OF-{0000}</displayFormat>
        <label>Unit progress Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Units progress</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

elearningProject/force-app/main/default/objects/Unit_progress__c/fields/Module_Progress__c.field-meta.xml
<CustomField>
    <fullName>Module_Progress__c</fullName>
    <label>Module Progress</label>
    <referenceTo>Module_Progress__c</referenceTo>
    <relationshipLabel>Units progress</relationshipLabel>
    <relationshipName>Units_progress</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

elearningProject/force-app/main/default/objects/Unit_progress__c/fields/Num_of_tries__c.field-meta.xml
<CustomField>
    <fullName>Num_of_tries__c</fullName>
    <label>Num of tries</label>
    <precision>2</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

elearningProject/force-app/main/default/objects/Unit_progress__c/fields/Unit__c.field-meta.xml
<CustomField>
    <fullName>Unit__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Unit</label>
    <referenceTo>Unit__c</referenceTo>
    <relationshipLabel>Units progress</relationshipLabel>
    <relationshipName>Units_progress</relationshipName>
    <type>Lookup</type>
</CustomField>

elearningProject/force-app/main/default/objects/Unit_progress__c/fields/Unit_completed__c.field-meta.xml
<CustomField>
    <fullName>Unit_completed__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Unit completed</label>
    <type>Checkbox</type>
</CustomField>

elearningProject/force-app/main/default/objects/Unit_progress__c/fields/Unit_Stage__c.field-meta.xml
<CustomField>
    <fullName>Unit_Stage__c</fullName>
    <label>Unit Stage</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Draft</fullName>
                <default>true</default>
                <label>Draft</label>
            </value>
            <value>
                <fullName>Answered</fullName>
            </value>
            <value>
                <fullName>Success</fullName>
            </value>
            <value>
                <fullName>Fail</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

elearningProject/force-app/main/default/classes/UnitService.cls
public class UnitService {
    public class CustomException extends Exception {}
    public static boolean registerUnitResponse(Id unitId, String jsonAnswer){
        Savepoint sp = Database.setSavePoint();
        try{
            //buscar unidad asociada al Id unitId
            Unit__c unit = [SELECT Module__c, (SELECT Id, Num_of_tries__c FROM Units_progress__r WHERE Module_Progress__r.User__c =: UserInfo.getUserId() ORDER BY Num_of_tries__c DESC LIMIT 1) ,(SELECT Id, Name FROM Questions__r) FROM Unit__c WHERE ID = :unitId];
            
            //verificamos si module_progress existe
            Module_Progress__c moduleResp = [SELECT ID FROM Module_Progress__c 
                                             WHERE Module__c=:unit.Module__c AND User__c=:UserInfo.getUserId() AND Module_Status__c = 'In Progress'];
            // si el Module_Progress__c no existe, lo creo
            if (moduleResp==NUll){
                //crear e insertar module_progress (primera unidad respondida)
                moduleResp = new Module_Progress__c(User__c=UserInfo.getUserId(), Module__c=unit.Module__c, Module_Status__c='In progress'); 
            	insert moduleResp;
            }
            
            //crear e insertar unit_progress
            Unit_progress__c unitResp = new Unit_progress__c(Unit__c=unitId, Module_Progress__c= moduleResp.Id , Unit_Stage__c='Draft');
            //NTH
            unitResp.Num_of_tries__c = !unit.Units_progress__r.isEmpty() ? unit.Units_progress__r[0].Num_of_tries__c + 1 : 1;
            insert unitResp;
            //Creo y cargo question_progress
            Map<Id,Id> answerMap = (Map<Id,Id>)JSON.deserializeStrict(jsonAnswer, Map<Id,Id>.class);
            List<Question_s_Answer__c> questionRespList = new List<Question_s_Answer__c>(); 
            for(Question__c question : unit.Questions__r){
                if(answerMap.containsKey(question.Id)){
                    Question_s_Answer__c questionResp = new Question_s_Answer__c(Question__c=question.Id,Unit_progress__c=unitResp.Id,Option__c=answerMap.get(question.Id));
                	questionRespList.add(questionResp);
                } else {
                    throw new CustomException('La pregunta ' + question.Name + ' no fue respondida y es requerida.');
                }
            }
            /*for(ID questionId : answerMap.keySet()){
                Question_s_Answer__c questionResp = new Question_s_Answer__c(Question__c=questionId,Unit_progress__c=unitResp.Id,Option__c=answerMap.get(questionId));
                questionRespList.add(questionResp);
            }*/
            insert questionRespList;
            
            // actualizamos el Unit_progress con Unit_Stage='Answered' para luego disparar el trigger de evaluacion
            unitResp.Unit_Stage__c = 'Answered';
            update unitResp;
            // consultar si es necesaria la query o se puede retornar directamente unitResp.Unit_completed__c
            return [SELECT Unit_completed__c FROM Unit_progress__c WHERE Id=:unitResp.Id].Unit_completed__c; 
            
        } catch (Exception e){
            Database.rollback(sp);
            throw e;
        }   
    }  
    //////////////////////////////////////////////// cambiar los valores de las variables y revisar
    public class TrailWrapper{
        //Constructor
        public TrailWrapper(Trail__c trail, List<Module__c> modules, Set<Id> passedModuleIds, Set<Id> passedUnitIds){
            this.trail = trail;
            this.modules = modules;
            this.passedModuleIds = passedModuleIds;
            this.passedUnitIds = passedUnitIds;
            this.progressTrail = passedModuleIds.size()*100 / modules.size();
        }
        //Configuracion
        @AuraEnabled
        public Trail__c trail; //Registro de Trail solicitado
        @AuraEnabled
        public List<Module__c> modules; //Módulos con Unidades relacionadas
        
        //Transaccional
        //@AuraEnabled
        public Set<Id> passedModuleIds; //Ids de módulos relacionados al Trail actual en los que el Alumno ya aprobó
        //@AuraEnabled
        public Set<Id> passedUnitIds; //Ids de Unidades relacionadas a módulos del Trail actual que el Alumno ya aprobó
        @AuraEnabled
        public Integer progressTrail; //Porcentaje de progreso del Alumno en el Trail     

    }

    //Metodos
    
    public TrailWrapper getTrailWrapper(Id trailId){

        //Instancio trail wrapper con trail y modulos
        TrailWrapper trailWrap = new TrailWrapper([SELECT Name, Description__c, Trail_Estimated_Time__c, Trail_Max_Score__c FROM Trail__c WHERE Id =: trailId], getModules(trailId), getModuleIdsCompleted(trailId), getUnitIdsCompleted(trailId));

        return trailWrap;
    }
        // esto lo agregue luego (borrar)
    public String getTrailName(Id trailId){

        Trail__c trail1 = [SELECT Name, Description__c FROM Trail__c WHERE Id =: trailId];

        return trail1.Name;
    }
        // borrar hasta aca

    private List<Module__c> getModules(Id trailId){
        //Busco modulos relacionados
        List<Trail_Module__c> trailModules = [SELECT Module__c FROM Trail_Module__c WHERE Trail__c =: trailId];
        Set<Id> moduleIds = new Set<Id>();
        for(Trail_Module__c trailModule : trailModules){
            moduleIds.add(trailModule.Module__c);
        }
        return [SELECT Name, (SELECT Name FROM Units__r) FROM Module__c WHERE Id in : moduleIds];
    }

    private Set<Id> getModuleIdsCompleted(Id trailId){
        List<Module_Progress__c> moduleResponses = [SELECT Module__c FROM Module_Progress__c WHERE Module_Status__c = 'Completed' AND Module__c IN :getModules(trailId) AND User__c =: Userinfo.getUserId()];
        Set<Id> completedModuleIds = new Set<Id>();
        for(Module_Progress__c moduleResp : moduleResponses){
            completedModuleIds.add(moduleResp.Module__c);
        }

        return completedModuleIds;
    }
    private Set<Id> getUnitIdsCompleted(Id trailId){
        List<Unit_progress__c> unitResponses = [SELECT Unit__c FROM Unit_progress__c WHERE Unit_completed__c = true AND UserId__c =: Userinfo.getUserId() AND Unit__r.Module__c IN :getModules (trailId)];
        Set<Id> completedUnitIds = new Set<Id>();
        for(Unit_progress__c unitResp : unitResponses){
            completedUnitIds.add(unitResp.Unit__c);
        }

        return completedUnitIds;
    }

    /**********Class UnitWrapper************/
    public class UnitWrapper{
        //varibles
        public Unit__c unit;
        public List<Question__c> questions;
        
        //Constructor
        public UnitWrapper(Unit__c unit, List<Question__c> questions){
            this.unit = unit;
            this.questions = questions;
        }
    }
    
    //UnitWrapper's Methods
    public UnitWrapper getUnitWrapper(Id unitId){

        //Query to Unit
        unit__c unit = [SELECT Id, Name, Content__c, Estimated_time__c, Max_Score__c, Test_Type__c 
                        FROM Unit__c 
                        WHERE Id = :unitId];
        
        List<Question__c> questionsList = [
            SELECT Id, Name, Query__c, (SELECT Id, Name, Description__c, isRight__c FROM Options__r) 
            FROM Question__c 
            WHERE Unit__c = :unitId];
                
        return new UnitWrapper(unit, questionsList);
    }
}